export const refs = {
  //   homeButton: document.querySelector('#homeButton'),
  homeButton: document.querySelector('#home_btn'),
  logo: document.querySelector('#header-logo'),
  //   myLibraryButton: document.querySelector('#myLibraryButton'),
  libraryButton: document.querySelector('#library_btn'),
  //   searchInput: document.querySelector('#search-form'),
  searchForm: document.querySelector('#search-form'),
  filmGallery: document.querySelector('#filmGallery'),
  filmCardModalWrap: document.querySelector('#filmCardModalWrap'),
  //     themeToggle: document.querySelector('#themeToggle'),
  pagination: document.querySelector('#pagination'),
  watched: document.querySelector('#watched'),
  queue: document.querySelector('#queue'),
  //     addToWatched: document.querySelector('#addToWatched'),
  //     addToQueue: document.querySelector('#addToQueue'),
  //     openFilmCardModalBtn: document.querySelector("[data-filmCardModal-open]"),
  //     closeFilmCardModalBtn: document.querySelector("[data-filmCardModal-close]"),
  //     filmCardModal: document.querySelector("[data-filmCardModal]"),
  //     openFooterModalBtn: document.querySelector("[data-footerModal-open]"),
  //     closeFooterModalBtn: document.querySelector("[data-footerModal-close]"),
  //     footerModal: document.querySelector("[data-footerModal]"),

  header: document.querySelector('#header'),
  homeCurrentPage: document.querySelector('#home-current-page'),

  libraryCurrentPage: document.querySelector('#library-current-page'),
  hederLibraryPage: document.querySelector('#header-library'),

  filmTesList: document.querySelector('.film-test-list'),
  modalCloseButton: document.querySelector('.modal-close_button'),
  modalCardDetail: document.querySelector('.film-detail-modal'),
  backdrop: document.querySelector('.backdrop'),
};
